import {test,expect} from '@playwright/test';
test('DailyPad full workflow',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:5173');await page.setViewportSize({width:1440,height:1100});
 await expect(page.getByText('هنوز کاری برای امروز نداری.')).toBeVisible();
 await page.screenshot({path:'tests/desktop.png',fullPage:true});
 await page.keyboard.press('t');await page.getByLabel('عنوان کار',{exact:true}).fill('نوشتن برنامه پروژه');await page.getByLabel('توضیحات',{exact:true}).fill('آماده‌سازی نسخه نخست');await page.getByLabel('اولویت',{exact:true}).selectOption('high');await page.getByLabel('ساعت',{exact:true}).fill('10:00');await page.getByLabel('یادآوری (اختیاری)').fill('2026-09-09T10:00');await page.getByRole('button',{name:'ذخیره کار',exact:true}).click();
 await expect(page.locator('.task-title').first()).toHaveText('نوشتن برنامه پروژه');
 await page.locator('.task-title').first().click();await page.getByLabel('عنوان کار',{exact:true}).fill('برنامه پروژه نهایی');await page.getByRole('button',{name:'ذخیره کار',exact:true}).click();await page.getByRole('button',{name:'تکمیل کار',exact:true}).first().click();
 await expect(page.locator('.task-row').first()).toHaveClass(/is-done/);
 await page.getByRole('button',{name:'گزینه‌های کار',exact:true}).first().click();await page.getByRole('button',{name:'حذف',exact:true}).click();
 await page.locator('.sidebar nav').getByRole('button',{name:'سطل زباله',exact:true}).click();await expect(page.getByText('برنامه پروژه نهایی',{exact:true})).toBeVisible();await page.getByRole('button',{name:'بازیابی',exact:true}).click();await expect(page.getByText('سطل زباله خالی است')).toBeVisible();
 await page.keyboard.press('n');await page.locator('.note-title-input').fill('ایده‌های تازه');await page.locator('.rich-editor').fill('یک یادداشت برای شروع بهتر روز');await expect(page.locator('.save-status')).toHaveText(/ذخیره شد/);await page.getByRole('button',{name:'بستن',exact:true}).first().click();
 await page.reload();await page.locator('.global-search input').fill('ایده‌های تازه');await expect(page.locator('.note-card')).toHaveCount(1);await page.locator('.note-card').click();await expect(page.locator('.rich-editor')).toHaveText('یک یادداشت برای شروع بهتر روز');await page.getByRole('button',{name:'بستن',exact:true}).first().click();
 await page.locator('.global-search input').fill('برنامه پروژه');await expect(page.locator('.task-row')).toHaveCount(1);await page.getByRole('button',{name:'پاک کردن جست‌وجو'}).click();
 await page.locator('.sidebar nav').getByRole('button',{name:'کارهای من'}).click();await page.getByRole('button',{name:'عقب‌افتاده',exact:true}).click();await expect(page.locator('.task-row')).toHaveCount(0);await page.getByRole('button',{name:'همه کارها',exact:true}).click();await expect(page.locator('.task-row')).toHaveCount(1);
 await page.getByRole('button',{name:'دسته جدید',exact:true}).first().click();await page.getByLabel('نام دسته').fill('پروژه جدید');await page.getByRole('button',{name:'ذخیره دسته',exact:true}).click();await expect(page.locator('.category-nav').getByText('پروژه جدید')).toBeVisible();
 await page.locator('.sidebar nav').getByRole('button',{name:'تقویم',exact:true}).click();await expect(page.locator('.calendar-cell')).toHaveCount(42);await page.getByRole('button',{name:'هفته',exact:true}).click();await expect(page.locator('.calendar-cell')).toHaveCount(7);await page.getByRole('button',{name:'روز',exact:true}).click();await expect(page.locator('.calendar-cell')).toHaveCount(1);
 await page.getByRole('button',{name:'تغییر پوسته'}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await page.locator('.sidebar nav').getByRole('button',{name:'عادت‌ها',exact:true}).click();await page.getByRole('button',{name:'عادت جدید',exact:true}).click();await page.getByLabel('نام عادت').fill('مطالعه روزانه');await page.getByRole('button',{name:'ذخیره عادت'}).click();await page.locator('.habit-days button').last().click();await expect(page.locator('.habit-name small')).toHaveText('۱ روز متوالی');
 await page.locator('.sidebar nav').getByRole('button',{name:'تنظیمات',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'خروجی JSON',exact:true}).click();const file=await download;await file.saveAs('tests/backup.json');await page.locator('input[type=file]').setInputFiles('tests/backup.json');await page.getByRole('button',{name:'ادغام داده‌ها',exact:true}).click();await expect(page.getByText('پشتیبان با موفقیت وارد شد')).toBeVisible();
 await page.locator('input[type=file]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":1}')});await expect(page.getByRole('status')).toContainText('فایل نامعتبر است');
 await page.getByRole('button',{name:'پاک کردن همه داده‌ها',exact:true}).click();await expect(page.getByText(/این کار قابل بازگشت نیست/)).toBeVisible();await page.getByRole('button',{name:'انصراف',exact:true}).click();
 await page.getByLabel('زبان برنامه').selectOption('en');await expect(page.locator('html')).toHaveAttribute('dir','ltr');await expect(page.getByRole('heading',{name:'Settings',exact:true})).toBeVisible();await page.getByLabel('App language').selectOption('fa');
 await page.getByRole('button',{name:'تغییر پوسته'}).click();await page.locator('.sidebar nav').getByRole('button',{name:'نمای کلی',exact:true}).click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tests/mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.getByRole('button',{name:'باز کردن منو'}).click();await expect(page.locator('.sidebar')).toHaveClass(/open/);await page.locator('.sidebar nav').getByRole('button',{name:'تقویم',exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 expect(errors).toEqual([]);
});

test('Archive, duplicate, reorder, reminders and editor controls',async({page})=>{
 await page.addInitScript(()=>{class MockNotification{static permission='granted';static requestPermission=async()=> 'granted';constructor(_title:string,_options?:any){}};(window as any).Notification=MockNotification});
 await page.goto('http://localhost:5173');
 const task=async(title:string)=>{await page.getByRole('button',{name:'کار جدید',exact:true}).click();await page.getByLabel('عنوان کار',{exact:true}).fill(title);await page.getByRole('button',{name:'ذخیره کار',exact:true}).click()};
 await task('اول');await task('دوم');await page.locator('.task-row').nth(1).dragTo(page.locator('.task-row').nth(0));await expect(page.locator('.task-title').first()).toHaveText('دوم');
 await page.getByRole('button',{name:'گزینه‌های کار',exact:true}).first().click();await page.getByRole('button',{name:'کپی کردن',exact:true}).click();await expect(page.locator('.task-row')).toHaveCount(3);
 await page.getByRole('button',{name:'تکمیل کار',exact:true}).first().click();await page.getByRole('button',{name:'گزینه‌های کار',exact:true}).first().click();await page.locator('.dropdown').getByRole('button',{name:'بایگانی',exact:true}).click();await page.locator('.sidebar nav').getByRole('button',{name:'بایگانی',exact:true}).click();await expect(page.locator('.collection-row')).toHaveCount(1);await page.getByRole('button',{name:'بازیابی',exact:true}).click();
 await page.keyboard.press('n');await page.locator('.note-title-input').fill('یادداشت آزمایشی');await page.locator('.rich-editor').fill('متن آزمایشی');await page.locator('.rich-editor').press('Control+a');await page.getByRole('button',{name:'پررنگ',exact:true}).click();await expect(page.locator('.rich-editor b')).toHaveText('متن آزمایشی');await page.getByRole('button',{name:'سنجاق کردن',exact:true}).click();await page.getByRole('button',{name:'کپی یادداشت',exact:true}).click();await page.getByRole('button',{name:'بایگانی',exact:true}).last().click();await expect(page.locator('.collection-row')).toHaveCount(1);await page.getByRole('button',{name:'بازیابی',exact:true}).click();
 await page.locator('.sidebar nav').getByRole('button',{name:'یادداشت‌ها',exact:true}).click();await expect(page.locator('.note-card')).toHaveCount(2);await page.locator('.note-card').first().click();await page.getByRole('button',{name:'حذف یادداشت',exact:true}).click();await page.locator('.sidebar nav').getByRole('button',{name:'سطل زباله',exact:true}).click();await page.getByRole('button',{name:'حذف دائمی',exact:true}).click();await expect(page.getByRole('alertdialog')).toBeVisible();await page.getByRole('button',{name:'بله، تأیید می‌کنم',exact:true}).click();await expect(page.getByText('سطل زباله خالی است')).toBeVisible();
 await page.locator('.sidebar nav').getByRole('button',{name:'تنظیمات',exact:true}).click();await page.getByRole('switch').click();await expect(page.getByRole('switch')).toHaveAttribute('aria-checked','true');await page.getByRole('switch').click();await expect(page.getByRole('switch')).toHaveAttribute('aria-checked','false');
 await page.keyboard.press('t');await page.getByLabel('عنوان کار',{exact:true}).fill('یادآوری آزمایشی');await page.getByLabel('یادآوری (اختیاری)').fill('2020-01-01T10:00');await page.getByRole('button',{name:'ذخیره کار',exact:true}).click();await expect(page.getByRole('status')).toContainText('یادآوری: یادآوری آزمایشی',{timeout:15000});
 await page.keyboard.press('/');await expect(page.locator('.global-search input')).toBeFocused();await page.keyboard.press('Escape');
 for(const width of [360,768,1280]){await page.setViewportSize({width,height:900});await page.waitForTimeout(300);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()}
});
