import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth, public to authenticated, anon;
grant execute on function auth.uid() to authenticated, anon;
insert into auth.users values ('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');`);
const schema=await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8');
await db.exec(schema);await db.exec(schema); // migrations are idempotent
const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
const workspace={version:1,tasks:[],notes:[],categories:[],habits:[],settings:{theme:'light',language:'fa',notifications:false,name:'A'}};
const setUser=async(id)=>{await db.exec('reset role; set role authenticated;');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id])};
await setUser(a);
let r=await db.query('select public.save_workspace($1::jsonb,0) as rev',[JSON.stringify(workspace)]);assert.equal(r.rows[0].rev,1);
r=await db.query('select public.save_workspace($1::jsonb,1) as rev',[JSON.stringify(workspace)]);assert.equal(r.rows[0].rev,2);
await assert.rejects(db.query('select public.save_workspace($1::jsonb,1)',[JSON.stringify(workspace)]),e=>e.code==='40001');
await setUser(b);assert.equal((await db.query('select * from public.workspaces')).rows.length,0);
await assert.rejects(db.query('insert into public.workspaces(user_id,data) values ($1,$2::jsonb)',[a,JSON.stringify(workspace)]),e=>e.code==='42501');
assert.equal((await db.query('update public.workspaces set revision=99 where user_id=$1 returning *',[a])).rows.length,0);
await db.query('select public.save_workspace($1::jsonb,0)',[JSON.stringify({...workspace,settings:{...workspace.settings,name:'B'}})]);
assert.equal((await db.query('select user_id from public.workspaces')).rows[0].user_id,b);
await assert.rejects(db.query('select public.save_workspace($1::jsonb,1)',[JSON.stringify({version:1})]),e=>e.code==='23514');
await db.exec('reset role; set role anon;');
await assert.rejects(db.query('select * from public.workspaces'),e=>e.code==='42501');
await assert.rejects(db.query('select public.save_workspace($1::jsonb,0)',[JSON.stringify(workspace)]),e=>e.code==='42501');
await setUser(a);assert.equal((await db.query('select revision from public.workspaces')).rows[0].revision,2);
await db.close();console.log('PASS: schema re-run, owner isolation, anonymous denial, cross-user write denial, payload check, optimistic revisions and stale-save conflict.');
