import React,{useCallback,useEffect,useRef,useState} from 'react';
import type {Session,User as AuthUser} from '@supabase/supabase-js';
import {ArrowLeft,ArrowRight,Check,CheckCheck,CheckCircle2,Cloud,CloudOff,Download,Eye,EyeOff,KeyRound,LoaderCircle,LockKeyhole,LogIn,LogOut,Mail,RefreshCw,ShieldCheck,Sparkles,UserRound,X,AlertCircle} from 'lucide-react';
import {type Data,initialData,repository,validate,download,iso} from './data';
import {cloud,configured,redirectUrl,authError,fetchWorkspace,saveWorkspace,cacheRead,cacheWrite,cacheKey,freshWorkspace} from './cloud';
import './auth.css';
export type WorkspaceProps={initial:Data;onPersist:(d:Data)=>boolean;accountPanel:React.ReactNode;syncBar:React.ReactNode;cloudStatus?:string;initialStorageError?:boolean};
type RenderApp=(props:WorkspaceProps)=>React.ReactNode;
const getLegacy=()=>{try{const raw=localStorage.getItem('dailypad-v1');return raw?validate(JSON.parse(raw)):null}catch{return null}};
const hasContent=(d:Data|null)=>!!d&&(d.tasks.length+d.notes.length+d.habits.length>0);
function Loading({text}:{text:string}){return <div className="auth-loading"><span className="brand-mark"><CheckCheck size={28}/></span><LoaderCircle className="spin" size={24}/><p>{text}</p></div>}
function SecretInput({label,value,onChange,autoComplete='current-password',id}:{label:string;value:string;onChange:(v:string)=>void;autoComplete?:string;id:string}){const[show,setShow]=useState(false);return <label htmlFor={id}>{label}<div className="secret-input"><input id={id} type={show?'text':'password'} autoComplete={autoComplete} required minLength={autoComplete==='new-password'?10:1} maxLength={128} value={value} onChange={e=>onChange(e.target.value)} dir="ltr"/><button type="button" aria-label={show?'پنهان کردن رمز / Hide password':'نمایش رمز / Show password'} aria-pressed={show} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>}

export function AuthRoot({children}:{children:RenderApp}){
 const [session,setSession]=useState<Session|null>(null),[checking,setChecking]=useState(!!cloud),[guest,setGuest]=useState(()=>{try{return sessionStorage.getItem('dailypad-guest')==='yes'}catch{return false}}),[lang,setLang]=useState<'fa'|'en'>('fa'),[mode,setMode]=useState<'login'|'signup'|'forgot'|'reset'>((new URLSearchParams(location.search).get('mode')==='recovery'||location.hash.includes('type=recovery'))?'reset':'login'),[authNotice,setAuthNotice]=useState('');
 const fa=lang==='fa',t=(f:string,e:string)=>fa?f:e;
 useEffect(()=>{let alive=true;if(!cloud)return;cloud.auth.getSession().then(({data,error})=>{if(!alive)return;if(error)setAuthNotice(authError(error,fa));setSession(data.session);setChecking(false)}).catch(e=>{if(alive){setAuthNotice(authError(e,fa));setChecking(false)}});const {data:{subscription}}=cloud.auth.onAuthStateChange((event,next)=>{if(!alive)return;setSession(next);setChecking(false);if(next){try{sessionStorage.removeItem('dailypad-guest')}catch{}}if(event==='PASSWORD_RECOVERY')setMode('reset');if(event==='SIGNED_OUT'){setGuest(false);setMode('login')}});const params=new URLSearchParams(location.hash.slice(1));if(params.has('error_description'))setAuthNotice(t('لینک معتبر نیست یا منقضی شده. یک لینک تازه درخواست کن.','The link is invalid or expired. Request a fresh link.'));return()=>{alive=false;subscription.unsubscribe()}},[]);
 useEffect(()=>{if(!session&&!guest){document.documentElement.dir=fa?'rtl':'ltr';document.documentElement.lang=lang;document.documentElement.dataset.theme='light'}},[lang,session,guest]);
 async function signOut(){if(!cloud)return;const {error}=await cloud.auth.signOut({scope:'local'});if(error)throw error;setSession(null);setMode('login')}
 if(checking)return <Loading text={t('در حال بررسی حساب…','Checking your session…')}/>;
 if(session&&mode!=='reset')return <CloudWorkspace key={session.user.id} user={session.user} onLogout={signOut} onPassword={()=>setMode('reset')}>{children}</CloudWorkspace>;
 if(guest&&!session)return <LocalWorkspace onLogin={()=>{try{sessionStorage.removeItem('dailypad-guest')}catch{}setGuest(false);setMode('login')}}>{children}</LocalWorkspace>;
 return <AuthScreen mode={mode} setMode={setMode} fa={fa} setLanguage={()=>setLang(fa?'en':'fa')} notice={authNotice} session={session} onGuest={()=>{try{sessionStorage.setItem('dailypad-guest','yes')}catch{}setGuest(true)}} onPasswordDone={()=>{setMode('login');history.replaceState(null,'',location.pathname);setAuthNotice('')}}/>;
}

function AuthScreen({mode,setMode,fa,setLanguage,notice,session,onGuest,onPasswordDone}:{mode:'login'|'signup'|'forgot'|'reset';setMode:(s:'login'|'signup'|'forgot'|'reset')=>void;fa:boolean;setLanguage:()=>void;notice:string;session:Session|null;onGuest:()=>void;onPasswordDone:()=>void}){
 const t=(f:string,e:string)=>fa?f:e;
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[cooldown,setCooldown]=useState(0);
 useEffect(()=>{setError('');setMessage('');setPassword('');setRepeat('')},[mode]);
 useEffect(()=>{if(!cooldown)return;const i=setTimeout(()=>setCooldown(c=>c-1),1000);return()=>clearTimeout(i)},[cooldown]);
 const validPassword=()=>{if(password.length<10||!/[A-Za-z\u0600-\u06ff]/.test(password)||!/[0-9\u06f0-\u06f9]/.test(password)){setError(t('رمز باید حداقل ۱۰ نویسه و شامل حرف و عدد باشد.','Use at least 10 characters including letters and numbers.'));return false}if(password!==repeat){setError(t('تکرار رمز با رمز عبور یکسان نیست.','The passwords do not match.'));return false}return true};
 async function submit(e:React.FormEvent){e.preventDefault();if(!cloud||busy)return;setError('');setMessage('');if((mode==='signup'||mode==='reset')&&!validPassword())return;setBusy(true);try{
 if(mode==='login'){const {error}=await cloud.auth.signInWithPassword({email:email.trim(),password});if(error)throw error}
 if(mode==='signup'){const {data,error}=await cloud.auth.signUp({email:email.trim(),password,options:{data:{display_name:name.trim()},emailRedirectTo:redirectUrl()}});if(error)throw error;if(!data.session){setMessage(t('اگر این ایمیل امکان ثبت‌نام داشته باشد، لینک تأیید برایش ارسال می‌شود. صندوق ورودی و پوشهٔ Spam را بررسی کن؛ سپس از بخش ورود وارد شو.','If this email is eligible, a confirmation link will be sent. Check your inbox and spam folder, then sign in.'));setCooldown(60);setPassword('');setRepeat('')}}
 if(mode==='forgot'){const {error}=await cloud.auth.resetPasswordForEmail(email.trim(),{redirectTo:redirectUrl(true)});if(error)throw error;setMessage(t('اگر حسابی با این ایمیل وجود داشته باشد، لینک بازیابی ارسال می‌شود. صندوق ورودی و Spam را بررسی کن.','If an account exists for this email, a recovery link will be sent. Check your inbox and spam folder.'));setCooldown(60)}
 if(mode==='reset'){if(!session)throw Error('session missing');const {error}=await cloud.auth.updateUser({password});if(error)throw error;setPassword('');setRepeat('');onPasswordDone()}
 }catch(e){setError(authError(e,fa))}finally{setBusy(false)}}
 async function resend(){if(!cloud||busy||cooldown)return;if(!email.trim()||!email.includes('@')){setError(t('ابتدا یک ایمیل معتبر وارد کن.','Enter a valid email first.'));return}setBusy(true);setError('');try{const {error}=await cloud.auth.resend({type:'signup',email:email.trim(),options:{emailRedirectTo:redirectUrl()}});if(error)throw error;setMessage(t('در صورت امکان، لینک تأیید دوباره ارسال شد. ایمیلت را بررسی کن.','If eligible, a confirmation link was sent. Check your email.'));setCooldown(60)}catch(e){setError(authError(e,fa))}finally{setBusy(false)}}
 const login=mode==='login',signup=mode==='signup',forgot=mode==='forgot',reset=mode==='reset';
 return <div className="auth-page" dir={fa?'rtl':'ltr'}><header className="auth-header"><div className="auth-brand"><span className="brand-mark"><CheckCheck size={24}/></span><strong>DailyPad<span>®</span></strong></div><button className="btn small" onClick={setLanguage}>{fa?'English':'فارسی'}</button></header><main className="auth-layout"><section className="auth-story"><span className="auth-eyebrow"><i/>{t('یک جای آرام، برای همهٔ روزهای تو','A CALM SPACE FOR ALL YOUR DAYS')}</span><h1>{t('فکرهایت همراهت.','Your thoughts, with you.')}<br/><em>{t('هر جا که باشی.','Wherever life takes you.')}</em></h1><p>{t('کارها، یادداشت‌ها و عادت‌هایت را در یک فضای شخصی جمع کن؛ با حساب خودت، روی دستگاه‌های مختلف ادامه بده.','Bring your tasks, notes, and habits into one personal space. Sign in and pick up where you left off, on any device.')}</p><div className="auth-art" aria-hidden="true"><div className="auth-orbit"/><div className="auth-orbit second"/><div className="auth-note"><div className="auth-note-date"><span/><i/><i/></div><div className="auth-note-line"><Check size={15}/><span/></div><div className="auth-note-line"><Check size={15}/><span/></div><div className="auth-note-line"><span className="square"/><span/></div><div className="auth-note-line"><span className="square"/><span/></div></div><div className="auth-cloud"><Cloud size={31}/><span className="cloud-tick"><Check size={11}/></span></div><span className="auth-spark">✦</span><span className="auth-spark small">✧</span></div><div className="auth-benefits"><span><ShieldCheck size={16}/>{t('فضای جدا برای هر حساب','Your own private workspace')}</span><span><Cloud size={16}/>{t('ذخیرهٔ ابری','Cloud storage')}</span><span><CheckCircle2 size={16}/>{t('شروع ساده','A simple start')}</span></div></section><section className="auth-card"><div className="auth-card-icon">{forgot||reset?<KeyRound size={24}/>:signup?<UserRound size={24}/>:<LogIn size={24}/>}</div><h2>{login?t('خوش برگشتی','Welcome back'):signup?t('یک شروع تازه','A fresh start'):forgot?t('رمزت را فراموش کردی؟','Forgot your password?'):t('رمز جدیدت را انتخاب کن','Choose your new password')}</h2><p className="auth-subtitle">{login?t('وارد شو؛ روزت همین‌جا منتظر توست.','Sign in. Your day is waiting for you.'):signup?t('حسابت را بساز و فضای خودت را داشته باش.','Create your account and make yourself at home.'):forgot?t('ایمیل حسابت را بنویس تا لینک بازیابی بگیری.','Enter your account email to request a recovery link.'):t('یک رمز قوی و متفاوت برای حسابت بنویس.','Use a strong, unique password for your account.')}</p>{(login||signup)&&<div className="auth-tabs"><button className={login?'selected':''} disabled={busy} onClick={()=>setMode('login')}>{t('ورود','Sign in')}</button><button className={signup?'selected':''} disabled={busy} onClick={()=>setMode('signup')}>{t('ساخت حساب','Create account')}</button></div>}
 {!configured&&<div className="auth-config" role="status"><AlertCircle size={18}/><div><strong>{t('اتصال حساب کاربری هنوز تنظیم نشده','Account connection is not configured')}</strong><p>{t('فایل .env را با آدرس و کلید عمومی Supabase پر کن و npm run dev را دوباره اجرا کن. راهنمای کامل در ACCOUNT-SETUP-fa.md قرار دارد.','Fill .env with your Supabase URL and public key, then restart npm run dev. See ACCOUNT-SETUP-fa.md.')}</p></div></div>}
 {(error||notice)&&<div className="auth-message error" role="alert"><AlertCircle size={17}/>{error||notice}</div>}{message&&<div className="auth-message success" role="status"><CheckCircle2 size={18}/>{message}</div>}
 {reset&&!session?<div className="auth-message error">{t('برای تغییر رمز، لینک بازیابی ایمیل را باز کن یا وارد حسابت شو.','Open the recovery email link or sign in before changing your password.')}</div>:<form onSubmit={submit}>
 {signup&&<label htmlFor="auth-name">{t('نام شما','Your name')}<input id="auth-name" autoComplete="name" required maxLength={50} value={name} onChange={e=>setName(e.target.value)} placeholder={t('چه صدایت کنیم؟','What should we call you?')}/></label>}
 {!reset&&<label htmlFor="auth-email">{t('ایمیل','Email')}<div className="auth-input-icon"><Mail size={17}/><input id="auth-email" type="email" dir="ltr" required autoComplete="email" maxLength={254} placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/></div></label>}
 {!forgot&&<SecretInput id="auth-password" label={t('رمز عبور','Password')} value={password} onChange={setPassword} autoComplete={login?'current-password':'new-password'}/>}
 {(signup||reset)&&<><p className="password-hint">{t('حداقل ۱۰ نویسه، شامل حرف و عدد','At least 10 characters, including letters and numbers')}</p><SecretInput id="auth-repeat" label={t('تکرار رمز عبور','Confirm password')} value={repeat} onChange={setRepeat} autoComplete="new-password"/></>}
 {login&&<button type="button" className="auth-forgot" onClick={()=>setMode('forgot')}>{t('رمزت را فراموش کردی؟','Forgot your password?')}</button>}
 <button className="btn primary auth-submit" type="submit" disabled={!configured||busy||(forgot&&cooldown>0)}>{busy?<LoaderCircle className="spin" size={18}/>:reset?<Check size={18}/>:fa?<ArrowLeft size={18}/>:<ArrowRight size={18}/>} {busy?t('کمی صبر کن…','Please wait…'):login?t('ورود به دیلی‌پد','Sign in to DailyPad'):signup?t('ساخت حساب کاربری','Create my account'):forgot?cooldown?t(`ارسال دوباره در ${cooldown} ثانیه`,`Resend in ${cooldown}s`):t('ارسال لینک بازیابی','Send recovery link'):t('ذخیره رمز جدید','Save new password')}</button></form>}
 {(login||signup)&&configured&&<button className="auth-resend" disabled={busy||cooldown>0} onClick={resend}>{cooldown?t(`ارسال مجدد پس از ${cooldown} ثانیه`,`Resend after ${cooldown}s`):t('ایمیل تأیید نرسیده؟ ارسال دوباره','No confirmation email? Resend it')}</button>}
 {(forgot||reset)&&<button className="auth-back" disabled={busy} onClick={()=>{setMode('login');if(reset)history.replaceState(null,'',location.pathname)}}>{t(session?'بازگشت به برنامه':'بازگشت به ورود',session?'Back to workspace':'Back to sign in')}</button>}
 {!session&&<div className="auth-local"><span>{t('فعلاً بدون حساب؟','Not ready for an account?')}</span><button onClick={onGuest}>{t('ورود به فضای محلی','Open local workspace')}</button><small>{t('فقط در همین مرورگر؛ بدون همگام‌سازی ابری','This browser only. No cloud sync.')}</small></div>}<p className="auth-security"><LockKeyhole size={12}/>{t('رمز عبور را Supabase Auth مدیریت می‌کند.','Passwords are managed by Supabase Auth.')}</p></section></main><footer className="auth-footer">{t('کمی منظم‌تر، خیلی آسوده‌تر.','A little more organized. A lot more at ease.')} <span>DailyPad</span></footer></div>
}

function LocalWorkspace({children,onLogin}:{children:RenderApp;onLogin:()=>void}){
 const [initial]=useState(()=>{try{return repository.load()}catch{return initialData()}}),[fa,setFa]=useState(initial.settings.language==='fa');const t=(f:string,e:string)=>fa?f:e;
 const persist=useCallback((d:Data)=>{setFa(d.settings.language==='fa');try{repository.save(d);return true}catch{return false}},[]);
 const panel=<section className="panel account-settings"><div className="account-avatar"><UserRound size={24}/></div><div className="account-info"><h2>{t('فضای محلی — بدون حساب','Local workspace — no account')}</h2><p>{t('اطلاعات فقط در همین مرورگر نگهداری می‌شود. برای ذخیرهٔ ابری وارد شو.','Your data stays in this browser. Sign in to save to the cloud.')}</p></div><button className="btn primary" onClick={onLogin}><LogIn size={16}/>{t('ورود یا ساخت حساب','Sign in or create account')}</button></section>;
 const bar=<div className="account-ribbon"><span><CloudOff size={14}/>{t('حالت محلی؛ بدون همگام‌سازی','Local mode · not synced')}</span><button onClick={onLogin}>{t('ورود / ساخت حساب','Sign in / create account')}<LogIn size={13}/></button></div>;
 return children({initial,onPersist:persist,accountPanel:panel,syncBar:bar,cloudStatus:'local'});
}

type SyncState='saved'|'saving'|'pending'|'error'|'conflict';
function CloudWorkspace({user,onLogout,onPassword,children}:{user:AuthUser;onLogout:()=>Promise<void>;onPassword:()=>void;children:RenderApp}){
 const [initial,setInitial]=useState<Data|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[status,setStatus]=useState<SyncState>('saved'),[detail,setDetail]=useState(''),[fa,setFa]=useState(true),[localError,setLocalError]=useState(false),[appKey,setAppKey]=useState(0),[confirm,setConfirm]=useState<'logout'|'reload'|'migrate'|null>(null),[busy,setBusy]=useState(false),[legacy,setLegacy]=useState(()=>getLegacy());
 const t=(f:string,e:string)=>fa?f:e;
 useEffect(()=>{if(!confirm)return;const before=document.activeElement as HTMLElement;const listener=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy){e.preventDefault();setConfirm(null)}if(e.key==='Tab'){const buttons=[...document.querySelectorAll<HTMLButtonElement>('.account-confirm button')].filter(b=>!b.disabled);const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',listener);return()=>{document.removeEventListener('keydown',listener);before?.focus()}},[confirm,busy]);
 const latest=useRef<Data|null>(null),revision=useRef(0),saved=useRef(''),queued=useRef<Data|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),flight=useRef<Promise<boolean>|null>(null),alive=useRef(true),blocked=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;if(timer.current)clearTimeout(timer.current)}},[]);
 const flush=useCallback(async():Promise<boolean>=>{if(flight.current)return flight.current;if(blocked.current)return false;if(!queued.current)return true;const work=async()=>{if(alive.current)setStatus('saving');while(queued.current&&alive.current){const payload=queued.current;try{const newRevision=await saveWorkspace(payload,revision.current);revision.current=newRevision;saved.current=JSON.stringify(payload);if(queued.current===payload)queued.current=null;try{cacheWrite(user.id,{data:queued.current||payload,revision:newRevision,dirty:!!queued.current});if(alive.current)setLocalError(false)}catch{if(alive.current)setLocalError(true)}}catch(e){const conflict=(e as {code?:string}).code==='40001'||String((e as Error).message).includes('WORKSPACE_CONFLICT');if(conflict)blocked.current=true;if(alive.current){setStatus(conflict?'conflict':'error');setDetail(authError(e));}return false}}if(alive.current){setStatus('saved');setDetail('')}return !queued.current};flight.current=work();try{return await flight.current}finally{flight.current=null}},[user.id]);
 const persist=useCallback((d:Data)=>{latest.current=d;setFa(d.settings.language==='fa');const dirty=JSON.stringify(d)!==saved.current;if(dirty){queued.current=d;if(!blocked.current)setStatus('pending')}let ok=true;try{cacheWrite(user.id,{data:d,revision:revision.current,dirty});setLocalError(false)}catch{ok=false;setLocalError(true)}if(dirty&&!blocked.current){if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),650)}return ok},[user.id,flush]);
 const load=useCallback(async(discardLocal=false)=>{setLoading(true);setLoadError('');try{const remote=await fetchWorkspace(user.id);if(!alive.current)return;const cache=discardLocal?null:cacheRead(user.id);const data=cache?.dirty?cache.data:remote.data||freshWorkspace(String(user.user_metadata?.display_name||''));revision.current=cache?.dirty?cache.revision:remote.revision;saved.current=remote.data?JSON.stringify(remote.data):'';blocked.current=false;queued.current=null;latest.current=data;setInitial(data);setFa(data.settings.language==='fa');setAppKey(k=>k+1);setStatus(JSON.stringify(data)===saved.current?'saved':'pending')}catch(e){if(alive.current)setLoadError(authError(e))}finally{if(alive.current)setLoading(false)}},[user.id]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(queued.current){e.preventDefault();e.returnValue=''}};const online=()=>{if(!blocked.current)void flush()};const hidden=()=>{if(document.visibilityState==='hidden'&&!blocked.current)void flush()};window.addEventListener('beforeunload',warn);window.addEventListener('online',online);document.addEventListener('visibilitychange',hidden);return()=>{window.removeEventListener('beforeunload',warn);window.removeEventListener('online',online);document.removeEventListener('visibilitychange',hidden)}},[flush]);
 async function logout(){setBusy(true);setDetail('');try{if(!await flush()){setDetail(t('خروج متوقف شد؛ تغییرات هنوز در ابر ذخیره نشده‌اند. اتصال را بررسی کن یا ابتدا پشتیبان بگیر.','Sign-out paused: changes are not synced. Check your connection or export a backup.'));return}await onLogout();try{localStorage.removeItem(cacheKey(user.id))}catch{}}catch(e){setDetail(authError(e,fa))}finally{if(alive.current){setBusy(false);setConfirm(null)}}}
 function backup(){if(latest.current)download('DailyPad-account-'+iso()+'.json',JSON.stringify(latest.current,null,2))}
 async function perform(){if(confirm==='logout'){await logout();return}if(confirm==='reload'){setBusy(true);if(flight.current)await flight.current;await load(true);setBusy(false)}if(confirm==='migrate'&&legacy&&latest.current){const old=latest.current;const merge=<T extends {id:string}>(a:T[],b:T[])=>[...new Map([...b,...a].map(x=>[x.id,x])).values()];const d:Data={...old,tasks:merge(old.tasks,legacy.tasks),notes:merge(old.notes,legacy.notes),habits:merge(old.habits,legacy.habits),categories:merge(old.categories,legacy.categories)};persist(d);setInitial(d);setAppKey(k=>k+1);setLegacy(null)}setConfirm(null)}
 if(loading)return <Loading text={t('در حال دریافت فضای شخصی تو…','Loading your workspace…')}/>;
 if(loadError||!initial)return <div className="account-load-error" dir={fa?'rtl':'ltr'}><AlertCircle size={32}/><h1>{t('فضای ابری باز نشد','Could not open your workspace')}</h1><p role="alert">{loadError}</p><p>{t('برای جلوگیری از جایگزین‌شدن اطلاعات، فضای خالی روی سرور ذخیره نکردیم.','To protect your data, no blank workspace was saved over your cloud data.')}</p><div><button className="btn primary" onClick={()=>void load()}><RefreshCw size={16}/>{t('تلاش دوباره','Retry')}</button><button className="btn" onClick={async()=>{try{await onLogout()}catch(e){setLoadError(authError(e,fa))}}}>{t('بازگشت به ورود','Back to sign in')}</button></div></div>;
 const label=status==='saved'?t('ذخیره‌شده در ابر','Saved to cloud'):status==='saving'?t('در حال همگام‌سازی…','Syncing…'):status==='pending'?t('در انتظار ذخیره…','Waiting to save…'):status==='conflict'?t('تداخل نسخه‌ها؛ نیاز به بررسی','Version conflict · review needed'):t('ذخیرهٔ ابری انجام نشد','Cloud save failed');
 const panel=<><section className="panel account-settings"><div className="account-avatar"><UserRound size={25}/></div><div className="account-info"><div className="account-heading"><h2>{t('حساب کاربری','Your account')}</h2><span className="account-verified"><ShieldCheck size={12}/>{user.email_confirmed_at?t('ایمیل تأییدشده','Email confirmed'):t('ایمیل تأییدنشده','Email not confirmed')}</span></div><p className="account-email" dir="ltr">{user.email}</p><small><Cloud size={12}/>{label}</small></div><div className="account-actions"><button className="btn" onClick={async()=>{if(await flush())onPassword()}}><KeyRound size={15}/>{t('تغییر رمز','Change password')}</button><button className="btn" onClick={()=>setConfirm('logout')}><LogOut size={15}/>{t('خروج از حساب','Sign out')}</button></div></section>{hasContent(legacy)&&<section className="panel migration-panel"><div><h3>{t('اطلاعات نسخهٔ محلی‌ات را همراهت بیاور','Bring your local workspace along')}</h3><p>{t('کارها، یادداشت‌ها، عادت‌ها و دسته‌ها با تأیید تو به همین حساب اضافه می‌شوند؛ نسخهٔ محلی حذف نمی‌شود.','Merge local tasks, notes, habits, and categories into this account. The local original will not be deleted.')}</p></div><button className="btn secondary" onClick={()=>setConfirm('migrate')}>{t('انتقال اطلاعات محلی','Import local workspace')}</button></section>}</>;
 const bar=<><div className={'account-ribbon cloud-ribbon '+status}><span>{status==='saving'||status==='pending'?<LoaderCircle className="spin" size={14}/>:status==='saved'?<Cloud size={14}/>:<CloudOff size={14}/>}<span aria-live="polite">{label}</span></span><div><span className="ribbon-email" dir="ltr">{user.email}</span>{(status==='error')&&<button onClick={()=>void flush()}><RefreshCw size={13}/>{t('تلاش دوباره','Retry')}</button>}<button onClick={()=>setConfirm('reload')} title={t('دریافت آخرین نسخهٔ ابری','Load latest cloud copy')}><RefreshCw size={13}/>{t('تازه‌سازی','Refresh')}</button><button onClick={()=>setConfirm('logout')}><LogOut size={13}/>{t('خروج','Sign out')}</button></div></div>{(status==='error'||status==='conflict'||localError||detail)&&<div className="cloud-error" role="alert"><AlertCircle size={18}/><div><strong>{localError?t('نسخهٔ پشتیبان مرورگر ذخیره نشد.','Browser backup could not be saved.'):status==='conflict'?t('اطلاعات دستگاه دیگری با این نسخه فرق دارد.','Another device has a different version.'):t('همگام‌سازی نیاز به توجه دارد.','Sync needs your attention.')}</strong><p>{status==='conflict'?t('برای جلوگیری از پاک‌شدن تغییرات، ذخیره متوقف شد. ابتدا از این نسخه خروجی بگیر، سپس نسخهٔ ابری را دریافت کن. در صورت نیاز، پشتیبان را در تنظیمات ادغام کن.','Saving was paused to prevent overwriting changes. Export this copy, refresh from the cloud, then merge your backup in Settings if needed.'):detail||t('پیش از بستن صفحه از اطلاعاتت خروجی بگیر.','Export your data before closing this page.')}</p></div><button className="btn small" onClick={backup}><Download size={14}/>{t('پشتیبان این نسخه','Export this copy')}</button></div>}</>;
 return <>{React.createElement(React.Fragment,{key:appKey},children({initial,onPersist:persist,accountPanel:panel,syncBar:bar,cloudStatus:status}))}{confirm&&<div className="overlay account-confirm"><div className="dialog" role="alertdialog" aria-modal="true" aria-labelledby="account-confirm-title"><h2 id="account-confirm-title">{confirm==='logout'?t('خروج از حساب؟','Sign out?'):confirm==='reload'?t('دریافت نسخهٔ ابری؟','Load the cloud copy?'):t('انتقال اطلاعات محلی به این حساب؟','Import local data into this account?')}</h2><p>{confirm==='logout'?t('پیش از خروج، تغییرات برای ذخیره به سرور فرستاده می‌شوند. پس از خروج موفق، نسخهٔ موقت این حساب از مرورگر پاک می‌شود؛ داده‌های ابری باقی می‌مانند.','Changes are synced before signing out. After successful sign-out, this account’s local cache is removed; cloud data remains.'):confirm==='reload'?t('نسخهٔ فعلی با آخرین اطلاعات سرور جایگزین می‌شود. اگر تغییری ذخیره نشده، ابتدا پشتیبان بگیر؛ تغییرات ذخیره‌نشده با تازه‌سازی کنار گذاشته می‌شوند.','This view will be replaced with the latest server data. Export a backup first: unsynced changes will be discarded by refreshing.'):t('اطلاعات همین مرورگر به حساب نمایش‌داده‌شده اضافه می‌شود. در شناسه‌های تکراری، نسخهٔ فعلی حساب حفظ خواهد شد.','Data from this browser will be added to the displayed account. Matching IDs keep the current account version.')}</p>{confirm==='migrate'&&<p className="confirm-email" dir="ltr">{user.email}</p>}{confirm==='reload'&&<button className="btn" onClick={backup}><Download size={15}/>{t('ابتدا پشتیبان بگیر','Export a backup first')}</button>}<div className="dialog-footer"><button className="btn" disabled={busy} onClick={()=>setConfirm(null)} autoFocus>{t('انصراف','Cancel')}</button><button className="btn primary" disabled={busy} onClick={()=>void perform()}>{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>} {t('تأیید','Confirm')}</button></div></div></div>}</>;
}
