export type Task = {id:string;title:string;description:string;date:string;time:string;priority:'low'|'medium'|'high';category:string;reminder:string;done:boolean;created:string;updated:string;completedAt?:string;archived?:boolean;deleted?:boolean;notified?:boolean};
export type Note = {id:string;title:string;content:string;category:string;color:string;pinned:boolean;created:string;updated:string;archived?:boolean;deleted?:boolean};
export type Category = {id:string;name:string;color:string;icon:string};
export type Habit = {id:string;title:string;icon:string;days:string[]};
export type Data = {version:1;tasks:Task[];notes:Note[];categories:Category[];habits:Habit[];settings:{theme:'light'|'dark'|'system';language:'fa'|'en';notifications:boolean;name:string}};
// randomUUID requires a secure context; getRandomValues also works on LAN HTTP.
// These IDs identify records only. They are not authentication/session tokens.
export function uid():string {
 if (typeof globalThis.crypto?.randomUUID === 'function') return globalThis.crypto.randomUUID();
 const bytes = new Uint8Array(16);
 globalThis.crypto.getRandomValues(bytes);
 bytes[6] = (bytes[6] & 0x0f) | 0x40;
 bytes[8] = (bytes[8] & 0x3f) | 0x80;
 const hex = Array.from(bytes, b => b.toString(16).padStart(2, '0')).join('');
 return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;
}
export function iso(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export function shift(date:string,n:number){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return iso(d)}
export const plain=(html:string)=>{const d=document.createElement('div');d.innerHTML=html.replace(/<br\s*\/?>/gi,'\n').replace(/<\/(p|div|h[1-6]|li|blockquote)>/gi,'\n</$1>');return d.textContent||''};
export function sanitize(html:string){const d=document.createElement('div');d.innerHTML=html;d.querySelectorAll('script,style,iframe,object,embed,svg,math,form,img,video,audio').forEach(e=>e.remove());d.querySelectorAll('*').forEach(el=>{for(const a of [...el.attributes]){if(a.name==='href'&&/^https?:\/\//i.test(a.value))continue;if(el.tagName==='INPUT'&&['type','checked','disabled'].includes(a.name))continue;el.removeAttribute(a.name)}if(el.tagName==='INPUT')el.setAttribute('type','checkbox')});return d.innerHTML}
export const palette=['#8970df','#5c9be6','#52ad91','#e9a558','#e17a9a','#a08b74'];
export function initialData():Data {const cats:Category[]=[{id:'work',name:'کار',color:palette[0],icon:'briefcase'},{id:'personal',name:'شخصی',color:palette[2],icon:'user'},{id:'study',name:'یادگیری',color:palette[1],icon:'book'},{id:'ideas',name:'ایده‌ها',color:palette[3],icon:'bulb'}];return {version:1,tasks:[],notes:[],categories:cats,habits:[],settings:{theme:'light',language:'fa',notifications:false,name:''}}}
export function validate(v:unknown):Data {if(!v||typeof v!=='object')throw Error('Invalid backup');const d=v as Data;if(d.version!==1||!['tasks','notes','habits','categories'].every(k=>Array.isArray((d as any)[k])))throw Error('Invalid backup');const str=(v:unknown)=>typeof v==='string';const date=(v:unknown)=>str(v)&&/^\d{4}-\d{2}-\d{2}$/.test(v as string)&&!isNaN(Date.parse(v as string));for(const key of ['tasks','notes','categories','habits'] as const){const ids=new Set();for(const x of d[key]){if(!x||!str(x.id)||ids.has(x.id))throw Error('Invalid IDs');ids.add(x.id)}}for(const key of ['tasks','notes'] as const)for(const x of d[key]){if(!x.id||!x.created||!x.updated||isNaN(Date.parse(x.created))||isNaN(Date.parse(x.updated)))throw Error('Invalid timestamp');for(const flag of ['deleted','archived'] as const)if(x[flag]!==undefined&&typeof x[flag]!=='boolean')throw Error('Invalid status')}for(const x of d.tasks){if(x.reminder&&isNaN(Date.parse(x.reminder)))throw Error('Invalid reminder');if(x.time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(x.time))throw Error('Invalid time');if(x.completedAt&&isNaN(Date.parse(x.completedAt)))throw Error('Invalid completion timestamp')}for(const x of d.tasks)if(![x.title,x.description,x.category,x.created,x.updated,x.time,x.reminder].every(str)||!date(x.date)||!['low','medium','high'].includes(x.priority)||typeof x.done!=='boolean')throw Error('Invalid task');for(const x of d.notes){if(![x.title,x.content,x.category,x.color,x.created,x.updated].every(str)||typeof x.pinned!=='boolean')throw Error('Invalid note');x.content=sanitize(x.content);if(!/^#[0-9a-f]{6}$/i.test(x.color))x.color='#f4efff'}for(const x of d.categories)if(![x.name,x.icon].every(str)||!/^#[0-9a-f]{6}$/i.test(x.color))throw Error('Invalid category');for(const x of d.habits)if(!str(x.title)||!str(x.icon)||!Array.isArray(x.days)||!x.days.every(date))throw Error('Invalid habit');if(!d.settings||!['light','dark','system'].includes(d.settings.theme)||!['fa','en'].includes(d.settings.language)||!str(d.settings.name)||typeof d.settings.notifications!=='boolean')throw Error('Invalid settings');return d}
export const repository={load():Data{const s=localStorage.getItem('dailypad-v1');return s?validate(JSON.parse(s)):initialData()},save(data:Data){localStorage.setItem('dailypad-v1',JSON.stringify(data))}};
export function streak(h:Habit){let d=iso(),n=0;if(!h.days.includes(d))d=shift(d,-1);while(h.days.includes(d)){n++;d=shift(d,-1)}return n}
export function download(name:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
